alter table application_events add constraint application_events_application_key unique (application_key);
alter table application_confirmation_emails add constraint application_confirmation_emails_application_key unique (application_key);
alter table application_reviews add constraint application_reviews_application_key unique (application_key);
