DROP VIEW latest_forms;

ALTER TABLE forms
ADD COLUMN locked TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN locked_by TEXT DEFAULT NULL;

CREATE VIEW latest_forms AS
SELECT DISTINCT ON (key) *
FROM forms
ORDER BY key, id DESC;