dist: xenial
language: java
jdk:
  - openjdk11
sudo: required
services:
  - docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "I2niWtIfrTcazhgkr3VcJnDv5dl1RaOXefHgGRmyYyry88oUvIRZz4owaAxCLyicNMWI08VFGNEOd2SGOiR9rNH1nuCy+04scE4o/VCCQmdlTACqvSgGCtkxH13qVqKU6kWINej0G4JN0cVkxFsIZOuqObQBWswN6bnT1bzt4b1zaaiPkU+apSZHDka1wZGve537W0J9pwMfuj9LUy00jA60rF8Fd+Fy1LbLKV3vySPhnp7DhdR8aU//z0+VScprAqzx5x2472T1bivDd2p2r+rmhC3j1vPXAUHOOvnRUeOYBKeuOQscnp1+ZO2RwTLCoJ/o25EkcEyqqZ6fOMOiKSskoWqSKuupPPIue4VisK2L88FBLemvEVBbo8k0Qr8GGg2jozPMlAUp5u7h8W0DeLOdLbUzJ2/xFfop3XGMMIp1erHM58Qzwforl2ijohSxOwhwUFYcPgQJixip4D7jKKUyonoW+hLrifYMAGZzPkNHyFgJKqNSBXUi9aWxLl4BO9Q1Be9QmMc9iZo2ZTHwya+KGNDFx7vmRySQ0f7boLwSo0hNNGwa8d4PB31n8c8Be0dlPXPpK2hAGjaVzk1IfZHpEsmaoiLlL1mINkScJQXyzZSBVeQGYhM9kg9OkJW3RhrEVoUmfGjpD6tzXCSUEkNBlSisWj2tMk0qvMmwU8Y="
    # AWS_SECRET_ACCESS_KEY
    - secure: "ALwZLXAq+lE3B92DZf9UiV3hd1q3ZPVi0HwAGTt6tX15MmvLBn6NrLdgThHIvBrHJKfPEFcP+W3iD19opkKxvqEZtEL2X7z4AvJps4RGcK4Tvm0AZ2c6s2xK2XFSmNLucRAOf+CpSV5d0+xOSvvw6bwKATP/ScmygoHdnlHBF0PEXui3NtLFxlP4Z+gJvrrzxvaxNBUaYC4Rvq7yUskLqIhVnCxzx/V1loMvuuqay3uaf7hRPJvn5SZZ17KgGNU9NFYzI5kwhhMli1F0euVJRcWjWilt1nNUhG9HK1AKH9KLn94xtMN+SHg0UrloD3KmQybZXAHKhUfaNQ2gdMuZRdDfyMqevUcCtGVLA3TodJzBP58u+D7Q7nyD2SWyh0dopEAauNGK7nv7SO94GeGY7dVbTYWXPr7XbGhZw9a33Yt46kDKqUMZFeiwWucjg3bCHKHvENEa2jTUW8p49d9tFq7CZrzV9INVyLssJR19vlY9U08jHW4EZB0xMxsPfJdVFAayp0wu2jUnoOZK+TG0f0IgZ0dUyrU2mSmhcAcva2B7zXVsVaXpHzqLPwd2SGJv3vKBy7+WpG5QEBnfZwz7kh/5GhkzXa9EuCs1et+jXO5cpmL3ohnau70CMFvGROiPZWytpRoQ4KbAWcIW5Ttg8W7lcsn4N48jEw9Kf/Fbrkk="

matrix:
  include:
    - stage: test
      name: "Cypress Tests"
      language: java
      jdk:
        - openjdk11
      services:
        - docker

      cache:
        directories:
          - $HOME/.m2

      install:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - source ci-tools/common/setup-tools.sh

      before_script:
        - docker run -d --name ataru-test-db -p 5433:5432 -e POSTGRES_DB=ataru-test -e POSTGRES_PASSWORD=oph -e POSTGRES_USER=oph 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:11
        - docker run -d --name ataru-test-redis -p 6380:6379 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/redis:5.0
        - docker run -d --name ataru-test-ftpd -p 2221:21 -p 30000-30009:30000-30009 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/hiekkalaatikko:ataru-test-ftpd

      script: >-
        nvm install &&
        nvm use &&
        ./bin/cibuild.sh run-browser-tests-cypress

    - stage: test
      name: "Spec And Mocha Tests"
      language: java
      jdk:
        - openjdk11
      services:
        - docker

      cache:
        directories:
          - $HOME/.m2

      before_install:
        - sudo apt-get update
        - sudo apt-get install -y lftp

      install:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - source ci-tools/common/setup-tools.sh

      before_script:
        - docker run -d --name ataru-test-db -p 5433:5432 -e POSTGRES_DB=ataru-test -e POSTGRES_PASSWORD=oph -e POSTGRES_USER=oph 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:11
        - docker run -d --name ataru-test-redis -p 6380:6379 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/redis:5.0
        - docker run -d --name ataru-test-ftpd -p 2221:21 -p 30000-30009:30000-30009 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/hiekkalaatikko:ataru-test-ftpd

      script: >-
        nvm install &&
        nvm use &&
        ./bin/cibuild.sh run-spec-and-mocha-tests


    - stage: test
      name: "Build Fatjar"
      language: java
      jdk:
        - openjdk11
      services:
        - docker

      cache:
        directories:
          - $HOME/.m2

      install:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - source ci-tools/common/setup-tools.sh

      script: >-
        ./bin/cibuild.sh create-uberjar &&
        export BASE_IMAGE="baseimage-fatjar-openjdk11:master" &&
        ./ci-tools/common/pull-image.sh &&
        cp -v ./target/ataru.jar $DOCKER_BUILD_DIR/artifact/ataru-editori.jar &&
        cp -vr ./oph-configuration $DOCKER_BUILD_DIR/config/ &&
        ./ci-tools/build/build-fatjar.sh ataru-editori &&
        ./ci-tools/build/upload-image.sh ataru-editori --skip-dynamo-write &&
        ./ci-tools/common/clean-docker-build-dir.sh &&
        cp -v ./target/ataru.jar $DOCKER_BUILD_DIR/artifact/ataru-hakija.jar &&
        cp -vr ./oph-configuration $DOCKER_BUILD_DIR/config/ &&
        ./ci-tools/build/build-fatjar.sh ataru-hakija &&
        ./ci-tools/build/upload-image.sh ataru-hakija --skip-dynamo-write

    - stage: deploy
      script:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - source ci-tools/common/setup-tools.sh
        - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
        - ./ci-tools/build/upload-image.sh ataru-editori --dynamo-write
        - ./ci-tools/build/upload-image.sh ataru-hakija --dynamo-write
