version: "3"
services:
  ataru-dev-db:
    build: ./test-postgres
    environment:
      - POSTGRES_DB=ataru-dev
      - POSTGRES_PASSWORD=oph
      - POSTGRES_USER=oph
    ports:
      - "15432:5432"
  ataru-dev-redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
  ataru-test-db:
    build: ./test-postgres
    environment:
      - POSTGRES_DB=ataru-test
      - POSTGRES_PASSWORD=oph
      - POSTGRES_USER=oph
    ports:
      - "15433:5432"
  ataru-test-ftpd:
    build: ./test-ftpd
    ports:
      - "1221:21"
      - "30000-30009:30000-30009"
  ataru-test-redis:
    image: "redis:latest"
    ports:
      - "16380:6379"
