packages:
  - .

minimumReleaseAge: 4320

overrides:
  body-parser: 1.20.3
  cross-spawn: 7.0.6
  form-data: 4.0.4
  minimatch: 3.0.5
  systeminformation: 5.27.12
  tar-fs: 2.1.4
  ua-parser-js: 0.7.35
  unzip-stream: 0.3.4

allowBuilds:
  clj-kondo: false
  cypress: false
