name: setup-node-env
description: 'Setup Node.js environment'
runs:
  using: 'composite'
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      with:
        package_json_file: package.json
        run_install: false
    - name: Setup Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: .nvmrc
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
