(ns ataru.application.harkinnanvaraisuus-types)

(def harkinnanvaraisuus-types
  ["SURE_YKS_MAT_AI"
   "SURE_EI_PAATTOTODISTUSTA"
   "ATARU_YKS_MAT_AI"
   "ATARU_ULKOMAILLA_OPISKELTU"
   "ATARU_EI_PAATTOTODISTUSTA"
   "ATARU_SOCIAL_REASONS"
   "ATARU_STUDY_CHALLENGES"
   "ATARU_CERTIFICATE_COMPARISON_DIFFICULTIES"
   "ATARU_INSUFFICIENT_LANGUAGE_SKILL"
   "NONE"])