(ns ataru.person-service.person-service-fixtures)

(def fake-person {:duplicate          false,
                  :sukupuoli          "2",
                  :passinnumero       nil,
                  :oppijanumero       nil,
                  :etunimet           "Hupu",
                  :yksilointiYritetty false,
                  :turvakielto        nil,
                  :asiointiKieli      nil,
                  :syntymaaika        "1996-04-12",
                  :kielisyys          [],
                  :created            1460441944943,
                  :henkiloTyyppi      "OPPIJA",
                  :modified           1460441944943,
                  :aidinkieli         {},
                  :kayttajatiedot     nil,
                  :sukunimi           "Ankka",
                  :eiSuomalaistaHetua false,
                  :kasittelijaOid     "1.2.246.562.24.84608031840",
                  :yksiloity          false,
                  :kansalaisuus       [],
                  :hetu               "120496-924J",
                  :oidHenkilo         "1.2.246.562.24.96282369159",
                  :passivoitu         false,
                  :kutsumanimi        "Hupu",
                  :yksiloityVTJ       false})
