#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

grep lockfileVersion package-lock.json | grep -qx '  "lockfileVersion": 1,' \
|| echo 'package-lock.json file format version is not 1!
Are you sure you are using the correct npm (6.14.16)?'
