name: Ataru

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-clojure-env

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Npm ci
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - run: npx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Prepare tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GA_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          docker run -d --name ataru-test-db -p 5433:5432 -e POSTGRES_DB=ataru-test -e POSTGRES_PASSWORD=oph -e POSTGRES_USER=oph 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:11
          docker run -d --name ataru-test-redis -p 6380:6379 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/redis:5.0
          docker run -d --name ataru-test-ftpd -p 2221:21 -p 30000-30009:30000-30009 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/hiekkalaatikko:ataru-test-ftpd

      - name: Run integration tests (Cypress & Playwright)
        run: |
          ./bin/cibuild.sh run-browser-tests-integration

  test-spec-and-mocha:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-clojure-env

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Prepare tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GA_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          docker run -d --name ataru-test-db -p 5433:5432 -e POSTGRES_DB=ataru-test -e POSTGRES_PASSWORD=oph -e POSTGRES_USER=oph 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:11
          docker run -d --name ataru-test-redis -p 6380:6379 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/redis:5.0
          docker run -d --name ataru-test-ftpd -p 2221:21 -p 30000-30009:30000-30009 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/hiekkalaatikko:ataru-test-ftpd

      - name: Run Spec and Mocha tests
        run: |
          ./bin/cibuild.sh run-spec-and-mocha-tests

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-clojure-env

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Build
        run: ./bin/cibuild.sh create-uberjar

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

  build-and-deploy-container:
    needs: [test-integration, test-spec-and-mocha, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

      - name: Build and deploy Docker containers
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          export BASE_IMAGE="baseimage-fatjar-openjdk17:master"
          ./ci-tools/common/pull-image.sh
          cp -v ./target/ataru.jar $DOCKER_BUILD_DIR/artifact/ataru-editori.jar
          cp -vr ./oph-configuration $DOCKER_BUILD_DIR/config/
          ./ci-tools/github-build/build-fatjar.sh ataru-editori
          ./ci-tools/common/clean-docker-build-dir.sh
          cp -v ./target/ataru.jar $DOCKER_BUILD_DIR/artifact/ataru-hakija.jar
          cp -vr ./oph-configuration $DOCKER_BUILD_DIR/config/
          ./ci-tools/github-build/build-fatjar.sh ataru-hakija
          ./ci-tools/github-build/upload-image.sh ataru-editori
          ./ci-tools/github-build/upload-image.sh ataru-hakija
